import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/navbar";
import Sidebar from "@/components/sidebar";
import Providers from "../providers/providers";
import { Toaster } from "@/components/ui/sonner"


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <div className="flex h-screen bg-gray-50">
            <Sidebar />
            <div className="flex-1 flex flex-col md:ml-64 ml-24">
              <Navbar />
              <main className="flex-1 overflow-y-auto p-5">
                {children}
              </main>
            </div>
          </div>
          <Toaster position="top-right" richColors/>
        </Providers>
      </body>
    </html>
  );
}
