import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/navbar";
import Sidebar from "@/components/sidebar";
import Providers from "../providers/providers";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <main className="w-full">
            <div className="flex min-h-screen bg-gray-50">
              <Sidebar />
              <div className="flex-1 md:ml-64 ml-24">
                <Navbar />
                <main className="mx-5">
                {children}
                </main>
              </div>
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
